source 'https://rubygems.org'
gemspec

# gem 'github-pages', group: :jekyll_plugins

# gem 'webrick'
# gem 'faraday-retry'
# gem 'wdm', '>= 0.1.0' if Gem.win_platform?
# gem "jekyll-theme-yat"
# gem 'jekyll-spaceship', group: :jekyll_plugins
